apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app        # <—— CHANGED
  template:
    metadata:
      labels:
        app: demo-app      # <—— CHANGED
    spec:
      containers:
      - name: demo-app
        image: sahana1478/demo-app2:126f5041893e716bd5a1703c98622d57e60c2444
        ports:
        - containerPort: 8080
